spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

logging:
  level:
    com.cesium.demo.mapper: debug